cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-start
  namespace: default
  labels:
    app: quick-start
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quick-start
  template:
    metadata:
      labels:
        app: quick-start
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: my-workload-identity
      containers:
      - name: test
        image: ImageName
        env:
          - name: kvBasUri
            value: https://myvault.vault.azure.net/
          - name: ClientId
            value: 00000000-0000-0000-0000-000000000000
        ports:
        - containerPort: 80
EOF