cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: my-workload-identity
  containers:
  - name: nginx
    image: ImageName
    env:
      - name: kvBasUri
        value: https://myvault.vault.azure.net/
    ports:
    - containerPort: 80
EOF