apiVersion: azconfig.io/v1beta1
kind: AzureAppConfigurationProvider
metadata:
  name: appconfigurationprovider-demo
spec:
  endpoint: https://juniwang-appc.azconfig.io
  target:
    configMapName: juniwang-configmap
  auth:
    managedIdentityClientId: a04a3b04-d8d9-4f27-a1f8-127b9c41d73f
  keyValues:
    keyVaults:
      auth:
        managedIdentityClientId: a04a3b04-d8d9-4f27-a1f8-127b9c41d73f
      target:
        secretName: juniwang-secrets